# This is a basic workflow to help you get started with Actions
name: CI2

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Run your pi-gen-action or any build steps here
      - name: Run pi-gen action
        uses: usimd/pi-gen-action@v1.9.0
        with:
          image-name: testpi-lot
          pi-gen-dir: /artifacts
          
        # Upload artifacts as a build output
        # Adjust the pattern to match your artifact files
      - uses: actions/upload-artifact@v2
        with:
          name: pi-gen-artifacts
          path: /artifacts/deploy/*.zip
